name = "Minimo"
license = "MIT"
licenselink = "https://github.com/template/template"
description = "Theme for template"
homepage = "https://template.github.io"
tags = [
  "blog",
  "minimal",
  "minimalist",
  "responsive",
  "google-analytics"
]
features = [
  "accessibility",
  "algolia",
  "analytics",
  "breadcrumbs",
  "comments",
  "cover-image",
  "disqus",
  "entry-navigation",
  "favicon",
  "fuse.js",
  "isso",
  "lunr.js",
  "multilingual",
  "multi-author",
  "opengraph",
  "pagination",
  "rtl",
  "search",
  "shortcodes",
  "sidebar",
  "single-column",
  "social-menu",
  "staticman",
  "syntax-highlighting",
  "table-of-contents",
  "utterances",
  "widgets"
]
min_version = 0.65

[author]
  name = "template"
  homepage = "https://template.github.io"
